name: NodeJS with Webpack

on:
    workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Use Node.js 20.x
      working-directory: ./GraphViewControl
      uses: actions/setup-node@v3
      with:
        node-version: 20.x

    - name: Build
      working-directory: ./GraphViewControl
      run: |
        npm install
        npm test
        npx webpack
